app/__init__.py
from flask import Flask
from config import config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)# 创建flask实例
    app.config.from_object(config[config_name])# 配置信息
    config[config_name].init_app(app)# 配置信息 可能 的初始化信息
    # 其他用到的插件初始化
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    #注册蓝本
    from .main import main
    app.register_blueprint(main)

    from .auth import auth
    app.register_blueprint(auth, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint


# 定义蓝本
main = Blueprint('main', __name__)
# 写在最后以防止循环引用
from . import views, errors

app/main/views.py
from . import main
from flask import render_template, request, url_for, make_response, flash, redirect, current_app
from .form import PostForm,DeleteForm
import os
from manager import app
import datetime
import random
from ..model import Article
from .. import db
from flask_login import login_required

def gen_rnd_filename():
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s' % (filename_prefix, str(random.randrange(1000, 10000)))

@main.route('/')
def index():
    return render_template("index.html")

@main.route('/blog')
def blog():
    #分页
    page = request.args.get('page',1,type=int)
    pagination = Article.query.order_by(Article.id.desc()).paginate(page,
                                                                  per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
                                                                  error_out=False)
    articles = pagination.items

    for article in articles:
        postition = article.article.find("</p>")
        article.article = article.article[:postition]
    return render_template("blog.html",articles=articles, pagination=pagination)


@main.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        article = Article(article=form.body.data)
        db.session.add(article)
        db.session.commit()
        flash("提交文章成功！")
        return redirect(url_for("main.post"))
    return render_template("post.html", form=form)

@main.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    form = DeleteForm()
    if form.validate_on_submit():
        article = Article.query.get_or_404(form.id.data)
        db.session.delete(article)
        db.session.commit()
        flash("成功删除文章")
    return render_template("delete.html",form=form)

@main.route('/me')
def me():
    return render_template("me.html")


@main.route('/article/<int:id>')
def article(id):
    article = Article.query.get_or_404(id)
    return render_template('article.html', article=article)

@main.route('/ckupload/', methods=['POST', 'OPTIONS'])
def ckupload():
    """CKEditor file upload"""
    error = ''
    url = ''
    callback = request.args.get("CKEditorFuncNum")

    if request.method == 'POST' and 'upload' in request.files:
        fileobj = request.files['upload']
        fname, fext = os.path.splitext(fileobj.filename)
        rnd_name = '%s%s' % (gen_rnd_filename(), fext)

        filepath = os.path.join(app.static_folder, 'upload', rnd_name)

        # 检查路径是否存在，不存在则创建
        dirname = os.path.dirname(filepath)
        if not os.path.exists(dirname):
            try:
                os.makedirs(dirname)
            except:
                error = 'ERROR_CREATE_DIR'
        elif not os.access(dirname, os.W_OK):
            error = 'ERROR_DIR_NOT_WRITEABLE'

        if not error:
            fileobj.save(filepath)
            url = url_for('static', filename='%s/%s' % ('upload', rnd_name))
    else:
        error = 'post error'

    res = """<script type="text/javascript">
  window.parent.CKEDITOR.tools.callFunction(%s, '%s', '%s');
</script>""" % (callback, url, error)

    response = make_response(res)
    response.headers["Content-Type"] = "text/html"
    return response


app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
<li{% if not pagination.has_prev %} class="disabled"{% endif %}>
<a href="{% if pagination.has_prev %}{{ url_for(endpoint,
page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
&laquo;
</a>
</li>
{% for p in pagination.iter_pages() %}
{% if p %}
{% if p == pagination.page %}
<li class="active">
<a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
</li>
{% else %}
<li>
<a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
</li>
{% endif %}
{% else %}
<li class="disabled"><a href="#">&hellip;</a></li>
{% endif %}
{% endfor %}
<li{% if not pagination.has_next %} class="disabled"{% endif %}>
<a href="{% if pagination.has_next %}{{ url_for(endpoint,
page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
&raquo;
</a>
</li>
</ul>
{% endmacro %}

app/templates/article.html
{%extends "base.html"%}

{%block title%}Rico's Blog{%endblock%}

{% block page_content %}

    <div class="page-header">
        <h1>详情</h1>
    </div>
    {{article.article|safe}}

{% endblock %}

app/templates/base.html
{%extends "bootstrap/base.html"%}

{%block head%}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
{%endblock%}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation" style="background-color:#66cccc;border-color:#ffffff;margin:0px;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="border-color:#ffffff">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="color:#FFFFFF">主页</a>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('main.blog')}}" style="color:#FFFFFF">博客</a></li>
                <li><a href="{{url_for('main.me')}}" style="color:#FFFFFF">关于我</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {%for message in get_flashed_messages()%}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{message}}
        </div>
    {%endfor%}

    {%block page_content%}{%endblock%}
</div>
{% endblock %}

app/templates/blog.html
{%extends "base.html"%}
{%import "_macros.html" as macros%}

{%block title%}Rico's Blog{%endblock%}

{% block page_content %}

    <div class="page-header">
        <h1>我的文章</h1>
    </div>
    <ul class="">
        {%for article in articles%}
        <li class="blog_li">
            <a href="{{url_for('main.article',id=article.id)}}">查看详情</a>
            <div class="article">
                {{article.article|safe}}
            </div>
        </li>
        {%endfor%}
    </ul>
    {{ macros.pagination_widget(pagination, '.blog')}}

{% endblock %}

app/templates/delete.html
{%extends "base.html"%}
{%import "bootstrap/wtf.html" as wtf %}

{%block title%}Rico's Blog{%endblock%}

{% block page_content %}

    <div class="page-header">
        <h1>Delete Page</h1>
    </div>
    {{wtf.quick_form(form)}}

{% endblock %}

app/templates/index.html
{%extends "base.html"%}

{%block title%}Rico's site{%endblock%}

{% block content %}
<div style="width:100%">
    <div style="width:100%;">
        <img src="{{url_for('static',filename='lake.gif')}}" style="width:100%">
    </div>
    <div>
        <center><h3>欢迎来到我的博客</h3></center>
        <center><p>纯手工建站不易，各位渗透大佬手下留情</p></center>
        <center><img src="{{url_for('static',filename='lowhead.jpg')}}" style="width:200px;height:180px"></center>
        <br><br>
        <center>powered by flask</center>
        <center>@Rico.Lee &nbsp;&nbsp;All Rights Reserved</center>
    </div>
</div>
{% endblock %}

app/templates/me.html
{%extends "base.html"%}

{%block title%}Rico's site{%endblock%}

{% block content %}
<div id="me_container">
    <div id="me_img" >
        <img src="{{url_for('static', filename='BikeAndMe.jpg')}}" width="300px" height="400px"><br>
        <a href="http://www.google.cn/maps/@39.0656016,117.1378801,983m/data=!3m1!1e3" target="_blank">2016夏/明理湖畔</a>
    </div>
    <div id="me_aboutme">
        <ul>
            <li>
                <img class="me_arrow" src="{{url_for('static',filename='arrow.PNG')}}"><h4 class="me_h">import 学历</h4>
                <ul>
                    <li>
                        ...毕业院校：天津理工大学
                    </li>
                    <li>
                        ...学历：本科
                    </li>
                    <li>
                        ...专业：信息安全
                    </li>
                </ul>
            </li>
            <li>
                <img class="me_arrow" src="{{url_for('static',filename='arrow.PNG')}}"><h4 class="me_h">import 技能/项目</h4>
                <ul>
                    <li>...语言：Python,Java,C,C#,Assembly(熟练程度DESC排序)</li>
                    <li>...框架：熟悉flask,了解.NET,Android</li>
                    <li>...安全：熟悉缓冲区溢出,常见WEB攻击渗透手段,其他网络攻击手段原理</li>
                    <li>...参与项目：“大学生创新创业”项目/Android分析工具（详见<a href="https://github.com/Ricochn/AndroidXMLAnalyse">
                        Github</a>）</li>
                </ul>
            </li>
            <li>
                <img class="me_arrow" src="{{url_for('static',filename='arrow.PNG')}}"><h4 class="me_h">import 实习经历</h4>
                <ul>
                    <li>...实训：南京壹进制公司/多数据库安全操作</li>
                </ul>
            </li>
            <li>
                <img class="me_arrow" src="{{url_for('static',filename='arrow.PNG')}}"><h4 class="me_h">import 其他</h4>
                <ul>
                    <li>...爱好：读书,瞎溜达 :)</li>
                </ul>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/post.html
{%extends "base.html"%}

{%import "bootstrap/wtf.html" as wtf%}

{%block head%}
{{super()}}
<script src="{{url_for('static', filename='ckeditor/ckeditor.js')}}"></script>
{%endblock%}

{%block page_content%}

    <div class="page-header">
        <h2>编辑博客</h2>
    </div>
    <form method="post">
        {{form.csrf_token}}
        {{form.body(class="ckeditor")| safe}}
        {{form.submit()}}
    </form>

{%endblock%}